### PR TITLE
replace go-charset with html/charset

### PR DESCRIPTION
**Pull request by mblakele**
Fix for #2

### CODE REVIEW

**Comment by mblakele** [comment]
@fredcy I'm testing this in my own deployment. If you get a chance, please verify that it fixes yours.

@harishjp FYI

**Comment by fredcy** [comment]
I checked out your mblakele-dev-charset branch and it builds cleanly for me.

**Comment by fredcy** [comment]
`go get` runs fine now, but I still have troubles deploying. May I open a separate issue about that? I have not built for appengine in many years and having trouble following the README.

**Comment by mblakele** [comment]
> `go get` runs fine now, but I still have troubles deploying. May I open a separate issue about that? I have not built for appengine in many years and having trouble following the README.

Yes, if it feels like a different problem please open a separate issue

**Pull request merged**
