### PR TITLE
port to go111

### PR DESCRIPTION
**Pull request by mblakele**
The original project has been archived. But I'm creating it as an FYI for @mjibson, and maybe it will help anyone else who wants to keep goread running past 2020-03-31, when google has announced EOL for apps running on versions of go prior to 1.11

While porting, I found it expedient to rip out support for the miniprofiler. I also converted datastore log entries to `log.*` calls, to reduce datastore usage. Sorry about that.

I also included some minor UI changes from my fork.

These changes have been running for a few days on my personal site: so far so good.

### CODE REVIEW

**Comment by mblakele** [comment]
@harishjp FYI — just saw https://github.com/mjibson/goread/pull/351

**Comment by harishjp** [comment]
Thanks @mblakele. I suppose this is better change.
* I was looking at logs cleanup, this eliminates the cleanup.
* And you have moved to request.Context, when I tried it was giving me errors in datastore read and write.

**Comment by mblakele** [comment]
> Thanks @mblakele. I suppose this is better change.

Feel free to use any of my changes. I see some things I like in your PR too. For example you didn't have to remove mpg. I may go back and revisit that.

**Comment by fredcy** [comment]
Thanks for this. I hope to continue using goread via my own app. But I can't seem to build using go 1.12. I get errors like this:

```
package code.google.com/p/go-charset/charset: unrecognized import path "code.google.com/p/go-charset/charset" (parse https://code.google.com/p/go-charset/charset?go-get=1: no go-import meta tags ())
package code.google.com/p/go-charset/data: unrecognized import path "code.google.com/p/go-charset/data" (parse https://code.google.com/p/go-charset/data?go-get=1: no go-import meta tags ())
```
I get the same when I use go 1.11.9. Any suggestions? Is there a better place to discuss this?

**Comment by mblakele** [comment]
> Thanks for this. I hope to continue using goread via my own app. But I can't seem to build using go 1.12. I get errors like this:
> 
> ```
> package code.google.com/p/go-charset/charset: unrecognized import path "code.google.com/p/go-charset/charset" (parse https://code.google.com/p/go-charset/charset?go-get=1: no go-import meta tags ())
> package code.google.com/p/go-charset/data: unrecognized import path "code.google.com/p/go-charset/data" (parse https://code.google.com/p/go-charset/data?go-get=1: no go-import meta tags ())
> ```
> 
> I get the same when I use go 1.11.9. Any suggestions? Is there a better place to discuss this?

Following up here: https://github.com/mblakele/goread/issues/2

**Pull request merged**
